baseURL = "https://www.anrosystems.com/"
languageCode = "en-au"
title = "ANRO Systems"

enableRobotsTXT = true

[params]
  company = "ANRO Systems"
  description = "Engineering, CAD, automation, and systems integration services."

[markup]
  [markup.goldmark.renderer]
    unsafe = true
